version: '2'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbit'
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 5s
            timeout: 10s
            retries: 10
    celery-rabbit-poc:
        environment:
            BROKER_SERVER: "rabbitmq"
        build: .
        ports:
            - "5000:5000"
        depends_on:
            rabbitmq:
                condition: service_healthy
        links:
            - rabbitmq
        networks:
            - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge